"""Add book_id FK to chapter.

Revision ID: 5cb963ea65d7
Revises: 77468abdf8c7
Create Date: 2016-12-12 09:23:35.436612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb963ea65d7'
down_revision = '77468abdf8c7'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'chapter', 'book_id', ['book_id'], ['book_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chapter', type_='foreignkey')
    ### end Alembic commands ###
