"""Create initial models.

Revision ID: b26ec77f035f
Revises: 
Create Date: 2016-12-12 10:37:58.972885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b26ec77f035f'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_id',
    sa.Column('book_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_table('metadata',
    sa.Column('book_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('rating', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('genres', sa.String(), nullable=True),
    sa.Column('characters', sa.String(), nullable=True),
    sa.Column('favorites', sa.Integer(), nullable=True),
    sa.Column('follows', sa.Integer(), nullable=True),
    sa.Column('published', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_table('review',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('chapter_number', sa.Integer(), nullable=True),
    sa.Column('review', sa.String(), nullable=True),
    sa.Column('published', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_table('chapter',
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('book_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('chapter_number', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('chapter', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book_id.book_id'], ),
    sa.PrimaryKeyConstraint('book_id', 'chapter_number')
    )
    op.create_table('metadata_html',
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('book_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('html', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book_id.book_id'], ),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_table('review_html',
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('book_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('review_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('html', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book_id.book_id'], ),
    sa.PrimaryKeyConstraint('book_id', 'review_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_html')
    op.drop_table('metadata_html')
    op.drop_table('chapter')
    op.drop_table('review')
    op.drop_table('metadata')
    op.drop_table('book_id')
    ### end Alembic commands ###
