---

version: '2'

services:

  db:

    image: postgres:9.6
    hostname: db

    ports:
      - '5432:5432'

    env_file:
      - postgres.env

  redis:
    image: redis:3.0.7

  fanfic:
    build: ./fanfic
